export default [
    "Avatar",
    "Pirates of the Caribbean",
    "The Dark Knight",
    "John Carter",
    "Quantum of Solace",
    "The Lone Ranger",
    "The Avengers",
    "Robin Hood",
    "King Kong",
    "Titanic",
    "Jurassic World",
    "Cars",
    "Toy Story",
    "The Great Gatsby",
    "Pacific Rim",
    "Hugo",
    "How to Train Your Dragon",
    "Inception",
    "The Prestige",
    "Interstellar",
    "Batman Begins",
    "Kung Fu Panda",
    "Armageddon",
    "Hulk",
    "Noah"
]